//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPLibrary.SCC016Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd", ConfigurationName="SCC016Reference.WSCC016")]
    public interface WSCC016 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação WSCC016 não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CIPLibrary.SCC016Reference.WSCC016Response1 WSCC016(CIPLibrary.SCC016Reference.WSCC016Request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CIPLibrary.SCC016Reference.WSCC016Response1> WSCC016Async(CIPLibrary.SCC016Reference.WSCC016Request1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd")]
    public partial class WSCC016Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoReqComplexType cabecalhoReqField;
        
        private WSCC016CorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoReqComplexType CabecalhoReq {
            get {
                return this.cabecalhoReqField;
            }
            set {
                this.cabecalhoReqField = value;
                this.RaisePropertyChanged("CabecalhoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC016CorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoReqComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlEmisField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrEmisField;
        
        private System.DateTime dtRefField;
        
        private string domSistField;
        
        private string nUOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
                this.RaisePropertyChanged("NumCtrlEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
                this.RaisePropertyChanged("ISPBEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
                this.RaisePropertyChanged("ISPBDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DtHrEmis {
            get {
                return this.dtHrEmisField;
            }
            set {
                this.dtHrEmisField = value;
                this.RaisePropertyChanged("DtHrEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
                this.RaisePropertyChanged("DtRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DomSist {
            get {
                return this.domSistField;
            }
            set {
                this.domSistField = value;
                this.RaisePropertyChanged("DomSist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUOp {
            get {
                return this.nUOpField;
            }
            set {
                this.nUOpField = value;
                this.RaisePropertyChanged("NUOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class Grupo_ASCC016RET_ResConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nUAvebcSCCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class Grupo_ASCC016RET_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identdPartAdmdoField;
        
        private string numCtrlConsigrioField;
        
        private string cNPJBaseEnteField;
        
        private string numConsigrioEnteField;
        
        private string numDigtConsigrioEnteField;
        
        private string numCtrlCIPField;
        
        private Grupo_ASCC016RET_ResConsigncComplexType grupo_ASCC016RET_ResConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
                this.RaisePropertyChanged("NumCtrlCIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Grupo_ASCC016RET_ResConsigncComplexType Grupo_ASCC016RET_ResConsignc {
            get {
                return this.grupo_ASCC016RET_ResConsigncField;
            }
            set {
                this.grupo_ASCC016RET_ResConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC016RET_ResConsignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class ASCC016RETComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC016RET_ConsigrioComplexType[] grupo_ASCC016RET_ConsigrioActoField;
        
        private Grupo_ASCC016_ConsigrioComplexType[] grupo_ASCC016RET_ConsigrioRecsdoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC016RET_Consigrio", IsNullable=false)]
        public Grupo_ASCC016RET_ConsigrioComplexType[] Grupo_ASCC016RET_ConsigrioActo {
            get {
                return this.grupo_ASCC016RET_ConsigrioActoField;
            }
            set {
                this.grupo_ASCC016RET_ConsigrioActoField = value;
                this.RaisePropertyChanged("Grupo_ASCC016RET_ConsigrioActo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC016_Consigrio", IsNullable=false)]
        public Grupo_ASCC016_ConsigrioComplexType[] Grupo_ASCC016RET_ConsigrioRecsdo {
            get {
                return this.grupo_ASCC016RET_ConsigrioRecsdoField;
            }
            set {
                this.grupo_ASCC016RET_ConsigrioRecsdoField = value;
                this.RaisePropertyChanged("Grupo_ASCC016RET_ConsigrioRecsdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class Grupo_ASCC016_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private ControleIF_CodErro numCtrlConsigrioField;
        
        private CNPJBase_CodErro cNPJBaseEnteField;
        
        private NumConsigrioEnte_CodErro numConsigrioEnteField;
        
        private NumDigtConsigrioEnte_CodErro numDigtConsigrioEnteField;
        
        private Grupo_ASCC016_ResConsigncComplexType grupo_ASCC016_ResConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ControleIF_CodErro NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CNPJBase_CodErro CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NumConsigrioEnte_CodErro NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NumDigtConsigrioEnte_CodErro NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC016_ResConsigncComplexType Grupo_ASCC016_ResConsignc {
            get {
                return this.grupo_ASCC016_ResConsigncField;
            }
            set {
                this.grupo_ASCC016_ResConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC016_ResConsignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class CNPJBase_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class ControleIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class NumConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class NumDigtConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class Grupo_ASCC016_ResConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NU_CodErro nUAvebcSCCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NU_CodErro NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd")]
    public partial class NU_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd")]
    public partial class WSCC016RETCorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ASCC016RETComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASCC016RET", Order=0)]
        public ASCC016RETComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoRespComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtHrRespostaField;
        
        private string statusProcessamentoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DtHrResposta {
            get {
                return this.dtHrRespostaField;
            }
            set {
                this.dtHrRespostaField = value;
                this.RaisePropertyChanged("DtHrResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusProcessamento {
            get {
                return this.statusProcessamentoField;
            }
            set {
                this.statusProcessamentoField = value;
                this.RaisePropertyChanged("StatusProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd")]
    public partial class WSCC016CorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC016_ConsigrioComplexType[] aSCC016Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC016_Consigrio", Namespace="http://www.cip-bancos.org.br/ARQ/ASCC016.xsd", IsNullable=false)]
        public Grupo_ASCC016_ConsigrioComplexType[] ASCC016 {
            get {
                return this.aSCC016Field;
            }
            set {
                this.aSCC016Field = value;
                this.RaisePropertyChanged("ASCC016");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd")]
    public partial class WSCC016Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoRespComplexType cabecalhoRespField;
        
        private WSCC016RETCorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoRespComplexType CabecalhoResp {
            get {
                return this.cabecalhoRespField;
            }
            set {
                this.cabecalhoRespField = value;
                this.RaisePropertyChanged("CabecalhoResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC016RETCorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC016Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd", Order=0)]
        public CIPLibrary.SCC016Reference.WSCC016Request WSCC016Request;
        
        public WSCC016Request1() {
        }
        
        public WSCC016Request1(CIPLibrary.SCC016Reference.WSCC016Request WSCC016Request) {
            this.WSCC016Request = WSCC016Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC016Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC016.xsd", Order=0)]
        public CIPLibrary.SCC016Reference.WSCC016Response WSCC016Response;
        
        public WSCC016Response1() {
        }
        
        public WSCC016Response1(CIPLibrary.SCC016Reference.WSCC016Response WSCC016Response) {
            this.WSCC016Response = WSCC016Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCC016Channel : CIPLibrary.SCC016Reference.WSCC016, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCC016Client : System.ServiceModel.ClientBase<CIPLibrary.SCC016Reference.WSCC016>, CIPLibrary.SCC016Reference.WSCC016 {
        
        public WSCC016Client() {
        }
        
        public WSCC016Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCC016Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC016Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC016Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIPLibrary.SCC016Reference.WSCC016Response1 CIPLibrary.SCC016Reference.WSCC016.WSCC016(CIPLibrary.SCC016Reference.WSCC016Request1 request) {
            return base.Channel.WSCC016(request);
        }
        
        public CIPLibrary.SCC016Reference.WSCC016Response WSCC016(CIPLibrary.SCC016Reference.WSCC016Request WSCC016Request) {
            CIPLibrary.SCC016Reference.WSCC016Request1 inValue = new CIPLibrary.SCC016Reference.WSCC016Request1();
            inValue.WSCC016Request = WSCC016Request;
            CIPLibrary.SCC016Reference.WSCC016Response1 retVal = ((CIPLibrary.SCC016Reference.WSCC016)(this)).WSCC016(inValue);
            return retVal.WSCC016Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CIPLibrary.SCC016Reference.WSCC016Response1> CIPLibrary.SCC016Reference.WSCC016.WSCC016Async(CIPLibrary.SCC016Reference.WSCC016Request1 request) {
            return base.Channel.WSCC016Async(request);
        }
        
        public System.Threading.Tasks.Task<CIPLibrary.SCC016Reference.WSCC016Response1> WSCC016Async(CIPLibrary.SCC016Reference.WSCC016Request WSCC016Request) {
            CIPLibrary.SCC016Reference.WSCC016Request1 inValue = new CIPLibrary.SCC016Reference.WSCC016Request1();
            inValue.WSCC016Request = WSCC016Request;
            return ((CIPLibrary.SCC016Reference.WSCC016)(this)).WSCC016Async(inValue);
        }
    }
}
