//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPLibrary.SCC011Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd", ConfigurationName="SCC011Reference.WSCC011")]
    public interface WSCC011 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação WSCC011 não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CIPLibrary.SCC011Reference.WSCC011Response1 WSCC011(CIPLibrary.SCC011Reference.WSCC011Request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CIPLibrary.SCC011Reference.WSCC011Response1> WSCC011Async(CIPLibrary.SCC011Reference.WSCC011Request1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd")]
    public partial class WSCC011Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoReqComplexType cabecalhoReqField;
        
        private WSCC011CorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoReqComplexType CabecalhoReq {
            get {
                return this.cabecalhoReqField;
            }
            set {
                this.cabecalhoReqField = value;
                this.RaisePropertyChanged("CabecalhoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC011CorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoReqComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlEmisField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrEmisField;
        
        private System.DateTime dtRefField;
        
        private string domSistField;
        
        private string nUOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
                this.RaisePropertyChanged("NumCtrlEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
                this.RaisePropertyChanged("ISPBEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
                this.RaisePropertyChanged("ISPBDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DtHrEmis {
            get {
                return this.dtHrEmisField;
            }
            set {
                this.dtHrEmisField = value;
                this.RaisePropertyChanged("DtHrEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
                this.RaisePropertyChanged("DtRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DomSist {
            get {
                return this.domSistField;
            }
            set {
                this.domSistField = value;
                this.RaisePropertyChanged("DomSist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUOp {
            get {
                return this.nUOpField;
            }
            set {
                this.nUOpField = value;
                this.RaisePropertyChanged("NUOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Grupo_ASCC011RET_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCPFServdrField;
        
        private string identcServdrField;
        
        private string identcOrgaoField;
        
        private string cNPJBaseOrgaoPagdrField;
        
        private string numOpConsigncConsigrioField;
        
        private string nUAvebcSCCField;
        
        private string numCtrlCIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string IdentcServdr {
            get {
                return this.identcServdrField;
            }
            set {
                this.identcServdrField = value;
                this.RaisePropertyChanged("IdentcServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string IdentcOrgao {
            get {
                return this.identcOrgaoField;
            }
            set {
                this.identcOrgaoField = value;
                this.RaisePropertyChanged("IdentcOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CNPJBaseOrgaoPagdr {
            get {
                return this.cNPJBaseOrgaoPagdrField;
            }
            set {
                this.cNPJBaseOrgaoPagdrField = value;
                this.RaisePropertyChanged("CNPJBaseOrgaoPagdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumOpConsigncConsigrio {
            get {
                return this.numOpConsigncConsigrioField;
            }
            set {
                this.numOpConsigncConsigrioField = value;
                this.RaisePropertyChanged("NumOpConsigncConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
                this.RaisePropertyChanged("NumCtrlCIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Grupo_ASCC011RET_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identdPartAdmdoField;
        
        private string numCtrlConsigrioField;
        
        private string cNPJBaseEnteField;
        
        private string numConsigrioEnteField;
        
        private string numDigtConsigrioEnteField;
        
        private Grupo_ASCC011RET_ConsigncComplexType grupo_ASCC011RET_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC011RET_ConsigncComplexType Grupo_ASCC011RET_Consignc {
            get {
                return this.grupo_ASCC011RET_ConsigncField;
            }
            set {
                this.grupo_ASCC011RET_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC011RET_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class ASCC011RETComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC011RET_ConsigrioComplexType[] grupo_ASCC011RET_ConsigrioActoField;
        
        private Grupo_ASCC011_ConsigrioComplexType[] grupo_ASCC011RET_ConsigrioRecsdoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC011RET_Consigrio", IsNullable=false)]
        public Grupo_ASCC011RET_ConsigrioComplexType[] Grupo_ASCC011RET_ConsigrioActo {
            get {
                return this.grupo_ASCC011RET_ConsigrioActoField;
            }
            set {
                this.grupo_ASCC011RET_ConsigrioActoField = value;
                this.RaisePropertyChanged("Grupo_ASCC011RET_ConsigrioActo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC011_Consigrio", IsNullable=false)]
        public Grupo_ASCC011_ConsigrioComplexType[] Grupo_ASCC011RET_ConsigrioRecsdo {
            get {
                return this.grupo_ASCC011RET_ConsigrioRecsdoField;
            }
            set {
                this.grupo_ASCC011RET_ConsigrioRecsdoField = value;
                this.RaisePropertyChanged("Grupo_ASCC011RET_ConsigrioRecsdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Grupo_ASCC011_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private ControleIF_CodErro numCtrlConsigrioField;
        
        private CNPJBase_CodErro cNPJBaseEnteField;
        
        private NumConsigrioEnte_CodErro numConsigrioEnteField;
        
        private NumDigtConsigrioEnte_CodErro numDigtConsigrioEnteField;
        
        private Grupo_ASCC011_ConsigncComplexType grupo_ASCC011_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ControleIF_CodErro NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CNPJBase_CodErro CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NumConsigrioEnte_CodErro NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NumDigtConsigrioEnte_CodErro NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC011_ConsigncComplexType Grupo_ASCC011_Consignc {
            get {
                return this.grupo_ASCC011_ConsigncField;
            }
            set {
                this.grupo_ASCC011_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC011_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class CNPJBase_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class ControleIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class NumConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class NumDigtConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Grupo_ASCC011_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CPF_CodErro numCPFServdrField;
        
        private IdentcServdr_CodErro identcServdrField;
        
        private IdentcOrgao_CodErro identcOrgaoField;
        
        private CNPJBase_CodErro cNPJBaseOrgaoPagdrField;
        
        private IdentcEsp_CodErro identcEspField;
        
        private TpParcmnt_CodErro tpParcmntField;
        
        private Qtd_CodErro qtdTotParclField;
        
        private Dia_CodErro diaVencParclField;
        
        private Data_CodErro dtIniAvebcField;
        
        private Data_CodErro dtFimAvebcField;
        
        private Valor_CodErro vlrParclField;
        
        private Valor_CodErro vlrTotAvebcField;
        
        private NumOpConsigncConsigrio_CodErro numOpConsigncConsigrioField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CPF_CodErro NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdentcServdr_CodErro IdentcServdr {
            get {
                return this.identcServdrField;
            }
            set {
                this.identcServdrField = value;
                this.RaisePropertyChanged("IdentcServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdentcOrgao_CodErro IdentcOrgao {
            get {
                return this.identcOrgaoField;
            }
            set {
                this.identcOrgaoField = value;
                this.RaisePropertyChanged("IdentcOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CNPJBase_CodErro CNPJBaseOrgaoPagdr {
            get {
                return this.cNPJBaseOrgaoPagdrField;
            }
            set {
                this.cNPJBaseOrgaoPagdrField = value;
                this.RaisePropertyChanged("CNPJBaseOrgaoPagdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public IdentcEsp_CodErro IdentcEsp {
            get {
                return this.identcEspField;
            }
            set {
                this.identcEspField = value;
                this.RaisePropertyChanged("IdentcEsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TpParcmnt_CodErro TpParcmnt {
            get {
                return this.tpParcmntField;
            }
            set {
                this.tpParcmntField = value;
                this.RaisePropertyChanged("TpParcmnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Qtd_CodErro QtdTotParcl {
            get {
                return this.qtdTotParclField;
            }
            set {
                this.qtdTotParclField = value;
                this.RaisePropertyChanged("QtdTotParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Dia_CodErro DiaVencParcl {
            get {
                return this.diaVencParclField;
            }
            set {
                this.diaVencParclField = value;
                this.RaisePropertyChanged("DiaVencParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Data_CodErro DtIniAvebc {
            get {
                return this.dtIniAvebcField;
            }
            set {
                this.dtIniAvebcField = value;
                this.RaisePropertyChanged("DtIniAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Data_CodErro DtFimAvebc {
            get {
                return this.dtFimAvebcField;
            }
            set {
                this.dtFimAvebcField = value;
                this.RaisePropertyChanged("DtFimAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Valor_CodErro VlrParcl {
            get {
                return this.vlrParclField;
            }
            set {
                this.vlrParclField = value;
                this.RaisePropertyChanged("VlrParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Valor_CodErro VlrTotAvebc {
            get {
                return this.vlrTotAvebcField;
            }
            set {
                this.vlrTotAvebcField = value;
                this.RaisePropertyChanged("VlrTotAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public NumOpConsigncConsigrio_CodErro NumOpConsigncConsigrio {
            get {
                return this.numOpConsigncConsigrioField;
            }
            set {
                this.numOpConsigncConsigrioField = value;
                this.RaisePropertyChanged("NumOpConsigncConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class CPF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class IdentcServdr_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class IdentcOrgao_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class IdentcEsp_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class TpParcmnt_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Qtd_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Dia_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Data_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class Valor_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd")]
    public partial class NumOpConsigncConsigrio_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd")]
    public partial class WSCC011RETCorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ASCC011RETComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASCC011RET", Order=0)]
        public ASCC011RETComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoRespComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtHrRespostaField;
        
        private string statusProcessamentoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DtHrResposta {
            get {
                return this.dtHrRespostaField;
            }
            set {
                this.dtHrRespostaField = value;
                this.RaisePropertyChanged("DtHrResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusProcessamento {
            get {
                return this.statusProcessamentoField;
            }
            set {
                this.statusProcessamentoField = value;
                this.RaisePropertyChanged("StatusProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd")]
    public partial class WSCC011CorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC011_ConsigrioComplexType[] aSCC011Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC011_Consigrio", Namespace="http://www.cip-bancos.org.br/ARQ/ASCC011.xsd", IsNullable=false)]
        public Grupo_ASCC011_ConsigrioComplexType[] ASCC011 {
            get {
                return this.aSCC011Field;
            }
            set {
                this.aSCC011Field = value;
                this.RaisePropertyChanged("ASCC011");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd")]
    public partial class WSCC011Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoRespComplexType cabecalhoRespField;
        
        private WSCC011RETCorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoRespComplexType CabecalhoResp {
            get {
                return this.cabecalhoRespField;
            }
            set {
                this.cabecalhoRespField = value;
                this.RaisePropertyChanged("CabecalhoResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC011RETCorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC011Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd", Order=0)]
        public CIPLibrary.SCC011Reference.WSCC011Request WSCC011Request;
        
        public WSCC011Request1() {
        }
        
        public WSCC011Request1(CIPLibrary.SCC011Reference.WSCC011Request WSCC011Request) {
            this.WSCC011Request = WSCC011Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC011Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC011.xsd", Order=0)]
        public CIPLibrary.SCC011Reference.WSCC011Response WSCC011Response;
        
        public WSCC011Response1() {
        }
        
        public WSCC011Response1(CIPLibrary.SCC011Reference.WSCC011Response WSCC011Response) {
            this.WSCC011Response = WSCC011Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCC011Channel : CIPLibrary.SCC011Reference.WSCC011, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCC011Client : System.ServiceModel.ClientBase<CIPLibrary.SCC011Reference.WSCC011>, CIPLibrary.SCC011Reference.WSCC011 {
        
        public WSCC011Client() {
        }
        
        public WSCC011Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCC011Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC011Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC011Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIPLibrary.SCC011Reference.WSCC011Response1 CIPLibrary.SCC011Reference.WSCC011.WSCC011(CIPLibrary.SCC011Reference.WSCC011Request1 request) {
            return base.Channel.WSCC011(request);
        }
        
        public CIPLibrary.SCC011Reference.WSCC011Response WSCC011(CIPLibrary.SCC011Reference.WSCC011Request WSCC011Request) {
            CIPLibrary.SCC011Reference.WSCC011Request1 inValue = new CIPLibrary.SCC011Reference.WSCC011Request1();
            inValue.WSCC011Request = WSCC011Request;
            CIPLibrary.SCC011Reference.WSCC011Response1 retVal = ((CIPLibrary.SCC011Reference.WSCC011)(this)).WSCC011(inValue);
            return retVal.WSCC011Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CIPLibrary.SCC011Reference.WSCC011Response1> CIPLibrary.SCC011Reference.WSCC011.WSCC011Async(CIPLibrary.SCC011Reference.WSCC011Request1 request) {
            return base.Channel.WSCC011Async(request);
        }
        
        public System.Threading.Tasks.Task<CIPLibrary.SCC011Reference.WSCC011Response1> WSCC011Async(CIPLibrary.SCC011Reference.WSCC011Request WSCC011Request) {
            CIPLibrary.SCC011Reference.WSCC011Request1 inValue = new CIPLibrary.SCC011Reference.WSCC011Request1();
            inValue.WSCC011Request = WSCC011Request;
            return ((CIPLibrary.SCC011Reference.WSCC011)(this)).WSCC011Async(inValue);
        }
    }
}
