//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CIPLibrary.SCC005Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd", ConfigurationName="SCC005Reference.WSCC005")]
    public interface WSCC005 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação WSCC005 não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CIPLibrary.SCC005Reference.WSCC005Response1 WSCC005(CIPLibrary.SCC005Reference.WSCC005Request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CIPLibrary.SCC005Reference.WSCC005Response1> WSCC005Async(CIPLibrary.SCC005Reference.WSCC005Request1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd")]
    public partial class WSCC005Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoReqComplexType cabecalhoReqField;
        
        private WSCC005CorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoReqComplexType CabecalhoReq {
            get {
                return this.cabecalhoReqField;
            }
            set {
                this.cabecalhoReqField = value;
                this.RaisePropertyChanged("CabecalhoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC005CorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoReqComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlEmisField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrEmisField;
        
        private System.DateTime dtRefField;
        
        private string domSistField;
        
        private string nUOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
                this.RaisePropertyChanged("NumCtrlEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
                this.RaisePropertyChanged("ISPBEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
                this.RaisePropertyChanged("ISPBDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DtHrEmis {
            get {
                return this.dtHrEmisField;
            }
            set {
                this.dtHrEmisField = value;
                this.RaisePropertyChanged("DtHrEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
                this.RaisePropertyChanged("DtRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DomSist {
            get {
                return this.domSistField;
            }
            set {
                this.domSistField = value;
                this.RaisePropertyChanged("DomSist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUOp {
            get {
                return this.nUOpField;
            }
            set {
                this.nUOpField = value;
                this.RaisePropertyChanged("NUOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Grupo_ASCC005RET_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlAvebcIFField;
        
        private string numCPFServdrField;
        
        private string identcServdrField;
        
        private string identcOrgaoField;
        
        private string cNPJOrgaoPagdrServdrField;
        
        private string nUAvebcSCCField;
        
        private string numCtrlCIPField;
        
        private System.DateTime dtProxProcmntArqDesctFolhaField;
        
        private bool dtProxProcmntArqDesctFolhaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlAvebcIF {
            get {
                return this.numCtrlAvebcIFField;
            }
            set {
                this.numCtrlAvebcIFField = value;
                this.RaisePropertyChanged("NumCtrlAvebcIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string IdentcServdr {
            get {
                return this.identcServdrField;
            }
            set {
                this.identcServdrField = value;
                this.RaisePropertyChanged("IdentcServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string IdentcOrgao {
            get {
                return this.identcOrgaoField;
            }
            set {
                this.identcOrgaoField = value;
                this.RaisePropertyChanged("IdentcOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CNPJOrgaoPagdrServdr {
            get {
                return this.cNPJOrgaoPagdrServdrField;
            }
            set {
                this.cNPJOrgaoPagdrServdrField = value;
                this.RaisePropertyChanged("CNPJOrgaoPagdrServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
                this.RaisePropertyChanged("NumCtrlCIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime DtProxProcmntArqDesctFolha {
            get {
                return this.dtProxProcmntArqDesctFolhaField;
            }
            set {
                this.dtProxProcmntArqDesctFolhaField = value;
                this.RaisePropertyChanged("DtProxProcmntArqDesctFolha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DtProxProcmntArqDesctFolhaSpecified {
            get {
                return this.dtProxProcmntArqDesctFolhaFieldSpecified;
            }
            set {
                this.dtProxProcmntArqDesctFolhaFieldSpecified = value;
                this.RaisePropertyChanged("DtProxProcmntArqDesctFolhaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Grupo_ASCC005RET_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identdPartAdmdoField;
        
        private string cNPJBaseEnteField;
        
        private string numConsigrioEnteField;
        
        private string numDigtConsigrioEnteField;
        
        private Grupo_ASCC005RET_ConsigncComplexType grupo_ASCC005RET_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Grupo_ASCC005RET_ConsigncComplexType Grupo_ASCC005RET_Consignc {
            get {
                return this.grupo_ASCC005RET_ConsigncField;
            }
            set {
                this.grupo_ASCC005RET_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC005RET_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class ASCC005RETComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC005RET_ConsigrioComplexType[] grupo_ASCC005RET_ConsigrioActoField;
        
        private Grupo_ASCC005_ConsigrioComplexType[] grupo_ASCC005RET_ConsigrioRecsdoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC005RET_Consigrio", IsNullable=false)]
        public Grupo_ASCC005RET_ConsigrioComplexType[] Grupo_ASCC005RET_ConsigrioActo {
            get {
                return this.grupo_ASCC005RET_ConsigrioActoField;
            }
            set {
                this.grupo_ASCC005RET_ConsigrioActoField = value;
                this.RaisePropertyChanged("Grupo_ASCC005RET_ConsigrioActo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC005_Consigrio", IsNullable=false)]
        public Grupo_ASCC005_ConsigrioComplexType[] Grupo_ASCC005RET_ConsigrioRecsdo {
            get {
                return this.grupo_ASCC005RET_ConsigrioRecsdoField;
            }
            set {
                this.grupo_ASCC005RET_ConsigrioRecsdoField = value;
                this.RaisePropertyChanged("Grupo_ASCC005RET_ConsigrioRecsdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Grupo_ASCC005_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private CNPJBase_CodErro cNPJBaseEnteField;
        
        private NumConsigrioEnte_CodErro numConsigrioEnteField;
        
        private NumDigtConsigrioEnte_CodErro numDigtConsigrioEnteField;
        
        private Grupo_ASCC005_ConsigncComplexType grupo_ASCC005_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CNPJBase_CodErro CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NumConsigrioEnte_CodErro NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NumDigtConsigrioEnte_CodErro NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Grupo_ASCC005_ConsigncComplexType Grupo_ASCC005_Consignc {
            get {
                return this.grupo_ASCC005_ConsigncField;
            }
            set {
                this.grupo_ASCC005_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC005_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class CNPJBase_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static implicit operator CNPJBase_CodErro(IdentcEsp_CodErro v)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class NumConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class NumDigtConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Grupo_ASCC005_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ControleIF_CodErro numCtrlAvebcIFField;
        
        private CPF_CodErro numCPFServdrField;
        
        private IdentcServdr_CodErro identcServdrField;
        
        private Data_CodErro dtNascmtoServdrField;
        
        private IdentcOrgao_CodErro identcOrgaoField;
        
        private CNPJ_CodErro cNPJOrgaoPagdrServdrField;
        
        private IdentcEsp_CodErro identcEspField;
        
        private Qtd_CodErro qtdTotParclField;
        
        private MesAno_CodErro vencPrimroParclField;
        
        private Dia_CodErro diaVencParclField;
        
        private Data_CodErro dtIniAvebcField;
        
        private Data_CodErro dtFimAvebcField;
        
        private Valor_CodErro vlrParclField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ControleIF_CodErro NumCtrlAvebcIF {
            get {
                return this.numCtrlAvebcIFField;
            }
            set {
                this.numCtrlAvebcIFField = value;
                this.RaisePropertyChanged("NumCtrlAvebcIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CPF_CodErro NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdentcServdr_CodErro IdentcServdr {
            get {
                return this.identcServdrField;
            }
            set {
                this.identcServdrField = value;
                this.RaisePropertyChanged("IdentcServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Data_CodErro DtNascmtoServdr {
            get {
                return this.dtNascmtoServdrField;
            }
            set {
                this.dtNascmtoServdrField = value;
                this.RaisePropertyChanged("DtNascmtoServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public IdentcOrgao_CodErro IdentcOrgao {
            get {
                return this.identcOrgaoField;
            }
            set {
                this.identcOrgaoField = value;
                this.RaisePropertyChanged("IdentcOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CNPJ_CodErro CNPJOrgaoPagdrServdr {
            get {
                return this.cNPJOrgaoPagdrServdrField;
            }
            set {
                this.cNPJOrgaoPagdrServdrField = value;
                this.RaisePropertyChanged("CNPJOrgaoPagdrServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public IdentcEsp_CodErro IdentcEsp {
            get {
                return this.identcEspField;
            }
            set {
                this.identcEspField = value;
                this.RaisePropertyChanged("IdentcEsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Qtd_CodErro QtdTotParcl {
            get {
                return this.qtdTotParclField;
            }
            set {
                this.qtdTotParclField = value;
                this.RaisePropertyChanged("QtdTotParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public MesAno_CodErro VencPrimroParcl {
            get {
                return this.vencPrimroParclField;
            }
            set {
                this.vencPrimroParclField = value;
                this.RaisePropertyChanged("VencPrimroParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Dia_CodErro DiaVencParcl {
            get {
                return this.diaVencParclField;
            }
            set {
                this.diaVencParclField = value;
                this.RaisePropertyChanged("DiaVencParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Data_CodErro DtIniAvebc {
            get {
                return this.dtIniAvebcField;
            }
            set {
                this.dtIniAvebcField = value;
                this.RaisePropertyChanged("DtIniAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Data_CodErro DtFimAvebc {
            get {
                return this.dtFimAvebcField;
            }
            set {
                this.dtFimAvebcField = value;
                this.RaisePropertyChanged("DtFimAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Valor_CodErro VlrParcl {
            get {
                return this.vlrParclField;
            }
            set {
                this.vlrParclField = value;
                this.RaisePropertyChanged("VlrParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class ControleIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class CPF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class IdentcServdr_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Data_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class IdentcOrgao_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class CNPJ_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class IdentcEsp_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Qtd_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class MesAno_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Dia_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd")]
    public partial class Valor_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd")]
    public partial class WSCC005RETCorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ASCC005RETComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASCC005RET", Order=0)]
        public ASCC005RETComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoRespComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtHrRespostaField;
        
        private string statusProcessamentoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DtHrResposta {
            get {
                return this.dtHrRespostaField;
            }
            set {
                this.dtHrRespostaField = value;
                this.RaisePropertyChanged("DtHrResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusProcessamento {
            get {
                return this.statusProcessamentoField;
            }
            set {
                this.statusProcessamentoField = value;
                this.RaisePropertyChanged("StatusProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd")]
    public partial class WSCC005CorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC005_ConsigrioComplexType[] aSCC005Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC005_Consigrio", Namespace="http://www.cip-bancos.org.br/ARQ/ASCC005.xsd", IsNullable=false)]
        public Grupo_ASCC005_ConsigrioComplexType[] ASCC005 {
            get {
                return this.aSCC005Field;
            }
            set {
                this.aSCC005Field = value;
                this.RaisePropertyChanged("ASCC005");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd")]
    public partial class WSCC005Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoRespComplexType cabecalhoRespField;
        
        private WSCC005RETCorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoRespComplexType CabecalhoResp {
            get {
                return this.cabecalhoRespField;
            }
            set {
                this.cabecalhoRespField = value;
                this.RaisePropertyChanged("CabecalhoResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC005RETCorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC005Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd", Order=0)]
        public CIPLibrary.SCC005Reference.WSCC005Request WSCC005Request;
        
        public WSCC005Request1() {
        }
        
        public WSCC005Request1(CIPLibrary.SCC005Reference.WSCC005Request WSCC005Request) {
            this.WSCC005Request = WSCC005Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC005Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC005.xsd", Order=0)]
        public CIPLibrary.SCC005Reference.WSCC005Response WSCC005Response;
        
        public WSCC005Response1() {
        }
        
        public WSCC005Response1(CIPLibrary.SCC005Reference.WSCC005Response WSCC005Response) {
            this.WSCC005Response = WSCC005Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCC005Channel : CIPLibrary.SCC005Reference.WSCC005, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCC005Client : System.ServiceModel.ClientBase<CIPLibrary.SCC005Reference.WSCC005>, CIPLibrary.SCC005Reference.WSCC005 {
        
        public WSCC005Client() {
        }
        
        public WSCC005Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCC005Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC005Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC005Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIPLibrary.SCC005Reference.WSCC005Response1 CIPLibrary.SCC005Reference.WSCC005.WSCC005(CIPLibrary.SCC005Reference.WSCC005Request1 request) {
            return base.Channel.WSCC005(request);
        }
        
        public CIPLibrary.SCC005Reference.WSCC005Response WSCC005(CIPLibrary.SCC005Reference.WSCC005Request WSCC005Request) {
            CIPLibrary.SCC005Reference.WSCC005Request1 inValue = new CIPLibrary.SCC005Reference.WSCC005Request1();
            inValue.WSCC005Request = WSCC005Request;
            CIPLibrary.SCC005Reference.WSCC005Response1 retVal = ((CIPLibrary.SCC005Reference.WSCC005)(this)).WSCC005(inValue);
            return retVal.WSCC005Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CIPLibrary.SCC005Reference.WSCC005Response1> CIPLibrary.SCC005Reference.WSCC005.WSCC005Async(CIPLibrary.SCC005Reference.WSCC005Request1 request) {
            return base.Channel.WSCC005Async(request);
        }
        
        public System.Threading.Tasks.Task<CIPLibrary.SCC005Reference.WSCC005Response1> WSCC005Async(CIPLibrary.SCC005Reference.WSCC005Request WSCC005Request) {
            CIPLibrary.SCC005Reference.WSCC005Request1 inValue = new CIPLibrary.SCC005Reference.WSCC005Request1();
            inValue.WSCC005Request = WSCC005Request;
            return ((CIPLibrary.SCC005Reference.WSCC005)(this)).WSCC005Async(inValue);
        }
    }
}
