//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPLibrary.SCC006Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd", ConfigurationName="SCC006Reference.WSCC006")]
    public interface WSCC006 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação WSCC006 não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CIPLibrary.SCC006Reference.WSCC006Response1 WSCC006(CIPLibrary.SCC006Reference.WSCC006Request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CIPLibrary.SCC006Reference.WSCC006Response1> WSCC006Async(CIPLibrary.SCC006Reference.WSCC006Request1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd")]
    public partial class WSCC006Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoReqComplexType cabecalhoReqField;
        
        private WSCC006CorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoReqComplexType CabecalhoReq {
            get {
                return this.cabecalhoReqField;
            }
            set {
                this.cabecalhoReqField = value;
                this.RaisePropertyChanged("CabecalhoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC006CorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoReqComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlEmisField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrEmisField;
        
        private System.DateTime dtRefField;
        
        private string domSistField;
        
        private string nUOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
                this.RaisePropertyChanged("NumCtrlEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
                this.RaisePropertyChanged("ISPBEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
                this.RaisePropertyChanged("ISPBDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DtHrEmis {
            get {
                return this.dtHrEmisField;
            }
            set {
                this.dtHrEmisField = value;
                this.RaisePropertyChanged("DtHrEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
                this.RaisePropertyChanged("DtRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DomSist {
            get {
                return this.domSistField;
            }
            set {
                this.domSistField = value;
                this.RaisePropertyChanged("DomSist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUOp {
            get {
                return this.nUOpField;
            }
            set {
                this.nUOpField = value;
                this.RaisePropertyChanged("NUOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Grupo_ASCC006RET_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlCIPField;
        
        private string nUAvebcSCCField;
        
        private string numContrtoIFField;
        
        private System.DateTime dtProxProcmntArqDesctFolhaField;
        
        private bool dtProxProcmntArqDesctFolhaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
                this.RaisePropertyChanged("NumCtrlCIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumContrtoIF {
            get {
                return this.numContrtoIFField;
            }
            set {
                this.numContrtoIFField = value;
                this.RaisePropertyChanged("NumContrtoIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime DtProxProcmntArqDesctFolha {
            get {
                return this.dtProxProcmntArqDesctFolhaField;
            }
            set {
                this.dtProxProcmntArqDesctFolhaField = value;
                this.RaisePropertyChanged("DtProxProcmntArqDesctFolha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DtProxProcmntArqDesctFolhaSpecified {
            get {
                return this.dtProxProcmntArqDesctFolhaFieldSpecified;
            }
            set {
                this.dtProxProcmntArqDesctFolhaFieldSpecified = value;
                this.RaisePropertyChanged("DtProxProcmntArqDesctFolhaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Grupo_ASCC006RET_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identdPartAdmdoField;
        
        private string numCtrlConsigrioField;
        
        private string cNPJBaseEnteField;
        
        private string numConsigrioEnteField;
        
        private string numDigtConsigrioEnteField;
        
        private Grupo_ASCC006RET_ConsigncComplexType grupo_ASCC006RET_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC006RET_ConsigncComplexType Grupo_ASCC006RET_Consignc {
            get {
                return this.grupo_ASCC006RET_ConsigncField;
            }
            set {
                this.grupo_ASCC006RET_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC006RET_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class ASCC006RETComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC006RET_ConsigrioComplexType[] grupo_ASCC006RET_ConsigrioActoField;
        
        private Grupo_ASCC006_ConsigrioComplexType[] grupo_ASCC006RET_ConsigrioRecsdoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC006RET_Consigrio", IsNullable=false)]
        public Grupo_ASCC006RET_ConsigrioComplexType[] Grupo_ASCC006RET_ConsigrioActo {
            get {
                return this.grupo_ASCC006RET_ConsigrioActoField;
            }
            set {
                this.grupo_ASCC006RET_ConsigrioActoField = value;
                this.RaisePropertyChanged("Grupo_ASCC006RET_ConsigrioActo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC006_Consigrio", IsNullable=false)]
        public Grupo_ASCC006_ConsigrioComplexType[] Grupo_ASCC006RET_ConsigrioRecsdo {
            get {
                return this.grupo_ASCC006RET_ConsigrioRecsdoField;
            }
            set {
                this.grupo_ASCC006RET_ConsigrioRecsdoField = value;
                this.RaisePropertyChanged("Grupo_ASCC006RET_ConsigrioRecsdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Grupo_ASCC006_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private ControleIF_CodErro numCtrlConsigrioField;
        
        private CNPJBase_CodErro cNPJBaseEnteField;
        
        private NumConsigrioEnte_CodErro numConsigrioEnteField;
        
        private NumDigtConsigrioEnte_CodErro numDigtConsigrioEnteField;
        
        private Grupo_ASCC006_ConsigncComplexType grupo_ASCC006_ConsigncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ControleIF_CodErro NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CNPJBase_CodErro CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NumConsigrioEnte_CodErro NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NumDigtConsigrioEnte_CodErro NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC006_ConsigncComplexType Grupo_ASCC006_Consignc {
            get {
                return this.grupo_ASCC006_ConsigncField;
            }
            set {
                this.grupo_ASCC006_ConsigncField = value;
                this.RaisePropertyChanged("Grupo_ASCC006_Consignc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class CNPJBase_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class ControleIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class NumConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class NumDigtConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Grupo_ASCC006_ConsigncComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CPF_CodErro numCPFServdrField;
        
        private NU_CodErro nUAvebcSCCField;
        
        private NumContrtoIF_CodErro numContrtoIFField;
        
        private Indr_CodErro indrAlongmtoField;
        
        private Indr_CodErro indrAvebcParclFlexvlField;
        
        private Grupo_ASCC006_ParclFlexComplexType[] grupo_ASCC006_ParclFlexField;
        
        private Taxa_CodErro taxNomlContrtoField;
        
        private Taxa_CodErro taxCETContrtoField;
        
        private Valor_CodErro vlrLibdConsigncField;
        
        private Valor_CodErro tarContrtoField;
        
        private Valor_CodErro tribContrtoField;
        
        private OtrEncargoContrto_CodErro otrEncargoContrtoField;
        
        private Valor_CodErro vlrTotContrtoField;
        
        private Valor_CodErro vlrParclFinlAvebcField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CPF_CodErro NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NU_CodErro NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NumContrtoIF_CodErro NumContrtoIF {
            get {
                return this.numContrtoIFField;
            }
            set {
                this.numContrtoIFField = value;
                this.RaisePropertyChanged("NumContrtoIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Indr_CodErro IndrAlongmto {
            get {
                return this.indrAlongmtoField;
            }
            set {
                this.indrAlongmtoField = value;
                this.RaisePropertyChanged("IndrAlongmto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Indr_CodErro IndrAvebcParclFlexvl {
            get {
                return this.indrAvebcParclFlexvlField;
            }
            set {
                this.indrAvebcParclFlexvlField = value;
                this.RaisePropertyChanged("IndrAvebcParclFlexvl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ASCC006_ParclFlex", Order=5)]
        public Grupo_ASCC006_ParclFlexComplexType[] Grupo_ASCC006_ParclFlex {
            get {
                return this.grupo_ASCC006_ParclFlexField;
            }
            set {
                this.grupo_ASCC006_ParclFlexField = value;
                this.RaisePropertyChanged("Grupo_ASCC006_ParclFlex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Taxa_CodErro TaxNomlContrto {
            get {
                return this.taxNomlContrtoField;
            }
            set {
                this.taxNomlContrtoField = value;
                this.RaisePropertyChanged("TaxNomlContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Taxa_CodErro TaxCETContrto {
            get {
                return this.taxCETContrtoField;
            }
            set {
                this.taxCETContrtoField = value;
                this.RaisePropertyChanged("TaxCETContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Valor_CodErro VlrLibdConsignc {
            get {
                return this.vlrLibdConsigncField;
            }
            set {
                this.vlrLibdConsigncField = value;
                this.RaisePropertyChanged("VlrLibdConsignc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Valor_CodErro TarContrto {
            get {
                return this.tarContrtoField;
            }
            set {
                this.tarContrtoField = value;
                this.RaisePropertyChanged("TarContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Valor_CodErro TribContrto {
            get {
                return this.tribContrtoField;
            }
            set {
                this.tribContrtoField = value;
                this.RaisePropertyChanged("TribContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public OtrEncargoContrto_CodErro OtrEncargoContrto {
            get {
                return this.otrEncargoContrtoField;
            }
            set {
                this.otrEncargoContrtoField = value;
                this.RaisePropertyChanged("OtrEncargoContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Valor_CodErro VlrTotContrto {
            get {
                return this.vlrTotContrtoField;
            }
            set {
                this.vlrTotContrtoField = value;
                this.RaisePropertyChanged("VlrTotContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Valor_CodErro VlrParclFinlAvebc {
            get {
                return this.vlrParclFinlAvebcField;
            }
            set {
                this.vlrParclFinlAvebcField = value;
                this.RaisePropertyChanged("VlrParclFinlAvebc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class CPF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class NU_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class NumContrtoIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Indr_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Grupo_ASCC006_ParclFlexComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MesAno_CodErro mesAnoParclField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MesAno_CodErro MesAnoParcl {
            get {
                return this.mesAnoParclField;
            }
            set {
                this.mesAnoParclField = value;
                this.RaisePropertyChanged("MesAnoParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class MesAno_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Taxa_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class Valor_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd")]
    public partial class OtrEncargoContrto_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd")]
    public partial class WSCC006RETCorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ASCC006RETComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASCC006RET", Order=0)]
        public ASCC006RETComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoRespComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtHrRespostaField;
        
        private string statusProcessamentoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DtHrResposta {
            get {
                return this.dtHrRespostaField;
            }
            set {
                this.dtHrRespostaField = value;
                this.RaisePropertyChanged("DtHrResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusProcessamento {
            get {
                return this.statusProcessamentoField;
            }
            set {
                this.statusProcessamentoField = value;
                this.RaisePropertyChanged("StatusProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd")]
    public partial class WSCC006CorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC006_ConsigrioComplexType[] aSCC006Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC006_Consigrio", Namespace="http://www.cip-bancos.org.br/ARQ/ASCC006.xsd", IsNullable=false)]
        public Grupo_ASCC006_ConsigrioComplexType[] ASCC006 {
            get {
                return this.aSCC006Field;
            }
            set {
                this.aSCC006Field = value;
                this.RaisePropertyChanged("ASCC006");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd")]
    public partial class WSCC006Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoRespComplexType cabecalhoRespField;
        
        private WSCC006RETCorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoRespComplexType CabecalhoResp {
            get {
                return this.cabecalhoRespField;
            }
            set {
                this.cabecalhoRespField = value;
                this.RaisePropertyChanged("CabecalhoResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC006RETCorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC006Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd", Order=0)]
        public CIPLibrary.SCC006Reference.WSCC006Request WSCC006Request;
        
        public WSCC006Request1() {
        }
        
        public WSCC006Request1(CIPLibrary.SCC006Reference.WSCC006Request WSCC006Request) {
            this.WSCC006Request = WSCC006Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC006Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC006.xsd", Order=0)]
        public CIPLibrary.SCC006Reference.WSCC006Response WSCC006Response;
        
        public WSCC006Response1() {
        }
        
        public WSCC006Response1(CIPLibrary.SCC006Reference.WSCC006Response WSCC006Response) {
            this.WSCC006Response = WSCC006Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCC006Channel : CIPLibrary.SCC006Reference.WSCC006, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCC006Client : System.ServiceModel.ClientBase<CIPLibrary.SCC006Reference.WSCC006>, CIPLibrary.SCC006Reference.WSCC006 {
        
        public WSCC006Client() {
        }
        
        public WSCC006Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCC006Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC006Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC006Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIPLibrary.SCC006Reference.WSCC006Response1 CIPLibrary.SCC006Reference.WSCC006.WSCC006(CIPLibrary.SCC006Reference.WSCC006Request1 request) {
            return base.Channel.WSCC006(request);
        }
        
        public CIPLibrary.SCC006Reference.WSCC006Response WSCC006(CIPLibrary.SCC006Reference.WSCC006Request WSCC006Request) {
            CIPLibrary.SCC006Reference.WSCC006Request1 inValue = new CIPLibrary.SCC006Reference.WSCC006Request1();
            inValue.WSCC006Request = WSCC006Request;
            CIPLibrary.SCC006Reference.WSCC006Response1 retVal = ((CIPLibrary.SCC006Reference.WSCC006)(this)).WSCC006(inValue);
            return retVal.WSCC006Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CIPLibrary.SCC006Reference.WSCC006Response1> CIPLibrary.SCC006Reference.WSCC006.WSCC006Async(CIPLibrary.SCC006Reference.WSCC006Request1 request) {
            return base.Channel.WSCC006Async(request);
        }
        
        public System.Threading.Tasks.Task<CIPLibrary.SCC006Reference.WSCC006Response1> WSCC006Async(CIPLibrary.SCC006Reference.WSCC006Request WSCC006Request) {
            CIPLibrary.SCC006Reference.WSCC006Request1 inValue = new CIPLibrary.SCC006Reference.WSCC006Request1();
            inValue.WSCC006Request = WSCC006Request;
            return ((CIPLibrary.SCC006Reference.WSCC006)(this)).WSCC006Async(inValue);
        }
    }
}
