//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPLibrary.SCC012Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd", ConfigurationName="SCC012Reference.WSCC012")]
    public interface WSCC012 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação WSCC012 não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CIPLibrary.SCC012Reference.WSCC012Response1 WSCC012(CIPLibrary.SCC012Reference.WSCC012Request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CIPLibrary.SCC012Reference.WSCC012Response1> WSCC012Async(CIPLibrary.SCC012Reference.WSCC012Request1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd")]
    public partial class WSCC012Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoReqComplexType cabecalhoReqField;
        
        private WSCC012CorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoReqComplexType CabecalhoReq {
            get {
                return this.cabecalhoReqField;
            }
            set {
                this.cabecalhoReqField = value;
                this.RaisePropertyChanged("CabecalhoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC012CorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoReqComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCtrlEmisField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrEmisField;
        
        private System.DateTime dtRefField;
        
        private string domSistField;
        
        private string nUOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
                this.RaisePropertyChanged("NumCtrlEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
                this.RaisePropertyChanged("ISPBEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
                this.RaisePropertyChanged("ISPBDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DtHrEmis {
            get {
                return this.dtHrEmisField;
            }
            set {
                this.dtHrEmisField = value;
                this.RaisePropertyChanged("DtHrEmis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
                this.RaisePropertyChanged("DtRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DomSist {
            get {
                return this.domSistField;
            }
            set {
                this.domSistField = value;
                this.RaisePropertyChanged("DomSist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUOp {
            get {
                return this.nUOpField;
            }
            set {
                this.nUOpField = value;
                this.RaisePropertyChanged("NUOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012RET_ParclContrtoSCCComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numParclField;
        
        private string vencParclField;
        
        private string numParclNaoDesavebdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string NumParcl {
            get {
                return this.numParclField;
            }
            set {
                this.numParclField = value;
                this.RaisePropertyChanged("NumParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VencParcl {
            get {
                return this.vencParclField;
            }
            set {
                this.vencParclField = value;
                this.RaisePropertyChanged("VencParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string NumParclNaoDesavebd {
            get {
                return this.numParclNaoDesavebdField;
            }
            set {
                this.numParclNaoDesavebdField = value;
                this.RaisePropertyChanged("NumParclNaoDesavebd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012RET_DesavebcComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numCPFServdrField;
        
        private string nUAvebcSCCField;
        
        private string numCtrlCIPField;
        
        private Grupo_ASCC012RET_ParclContrtoSCCComplexType grupo_ASCC012RET_ParclContrtoSCCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
                this.RaisePropertyChanged("NumCtrlCIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Grupo_ASCC012RET_ParclContrtoSCCComplexType Grupo_ASCC012RET_ParclContrtoSCC {
            get {
                return this.grupo_ASCC012RET_ParclContrtoSCCField;
            }
            set {
                this.grupo_ASCC012RET_ParclContrtoSCCField = value;
                this.RaisePropertyChanged("Grupo_ASCC012RET_ParclContrtoSCC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012RET_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identdPartAdmdoField;
        
        private string numCtrlConsigrioField;
        
        private string cNPJBaseEnteField;
        
        private string numConsigrioEnteField;
        
        private string numDigtConsigrioEnteField;
        
        private Grupo_ASCC012RET_DesavebcComplexType grupo_ASCC012RET_DesaverbcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC012RET_DesavebcComplexType Grupo_ASCC012RET_Desaverbc {
            get {
                return this.grupo_ASCC012RET_DesaverbcField;
            }
            set {
                this.grupo_ASCC012RET_DesaverbcField = value;
                this.RaisePropertyChanged("Grupo_ASCC012RET_Desaverbc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class ASCC012RETComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC012RET_ConsigrioComplexType[] grupo_ASCC012RET_ConsigrioActoField;
        
        private Grupo_ASCC012_ConsigrioComplexType[] grupo_ASCC012RET_ConsigrioRecsdoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC012RET_Consigrio", IsNullable=false)]
        public Grupo_ASCC012RET_ConsigrioComplexType[] Grupo_ASCC012RET_ConsigrioActo {
            get {
                return this.grupo_ASCC012RET_ConsigrioActoField;
            }
            set {
                this.grupo_ASCC012RET_ConsigrioActoField = value;
                this.RaisePropertyChanged("Grupo_ASCC012RET_ConsigrioActo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC012_Consigrio", IsNullable=false)]
        public Grupo_ASCC012_ConsigrioComplexType[] Grupo_ASCC012RET_ConsigrioRecsdo {
            get {
                return this.grupo_ASCC012RET_ConsigrioRecsdoField;
            }
            set {
                this.grupo_ASCC012RET_ConsigrioRecsdoField = value;
                this.RaisePropertyChanged("Grupo_ASCC012RET_ConsigrioRecsdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012_ConsigrioComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private ControleIF_CodErro numCtrlConsigrioField;
        
        private CNPJBase_CodErro cNPJBaseEnteField;
        
        private NumConsigrioEnte_CodErro numConsigrioEnteField;
        
        private NumDigtConsigrioEnte_CodErro numDigtConsigrioEnteField;
        
        private Grupo_ASCC012_DesavebcComplexType grupo_ASCC012_DesavebcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
                this.RaisePropertyChanged("IdentdPartAdmdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ControleIF_CodErro NumCtrlConsigrio {
            get {
                return this.numCtrlConsigrioField;
            }
            set {
                this.numCtrlConsigrioField = value;
                this.RaisePropertyChanged("NumCtrlConsigrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CNPJBase_CodErro CNPJBaseEnte {
            get {
                return this.cNPJBaseEnteField;
            }
            set {
                this.cNPJBaseEnteField = value;
                this.RaisePropertyChanged("CNPJBaseEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NumConsigrioEnte_CodErro NumConsigrioEnte {
            get {
                return this.numConsigrioEnteField;
            }
            set {
                this.numConsigrioEnteField = value;
                this.RaisePropertyChanged("NumConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NumDigtConsigrioEnte_CodErro NumDigtConsigrioEnte {
            get {
                return this.numDigtConsigrioEnteField;
            }
            set {
                this.numDigtConsigrioEnteField = value;
                this.RaisePropertyChanged("NumDigtConsigrioEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Grupo_ASCC012_DesavebcComplexType Grupo_ASCC012_Desavebc {
            get {
                return this.grupo_ASCC012_DesavebcField;
            }
            set {
                this.grupo_ASCC012_DesavebcField = value;
                this.RaisePropertyChanged("Grupo_ASCC012_Desavebc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class CNPJBase_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class ControleIF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class NumConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class NumDigtConsigrioEnte_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012_DesavebcComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CPF_CodErro numCPFServdrField;
        
        private IdentcServdr_CodErro identcServdrField;
        
        private IdentcOrgao_CodErro identcOrgaoField;
        
        private CNPJBase_CodErro cNPJBaseOrgaoPagdrField;
        
        private NU_CodErro nUAvebcSCCField;
        
        private IdentcMotvDesavebcContrto_CodErro identcMotvDesavebcContrtoField;
        
        private Grupo_ASCC012_ParclContrtoSCComplexType grupo_ASCC012_ParclContrtoSCCField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CPF_CodErro NumCPFServdr {
            get {
                return this.numCPFServdrField;
            }
            set {
                this.numCPFServdrField = value;
                this.RaisePropertyChanged("NumCPFServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdentcServdr_CodErro IdentcServdr {
            get {
                return this.identcServdrField;
            }
            set {
                this.identcServdrField = value;
                this.RaisePropertyChanged("IdentcServdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdentcOrgao_CodErro IdentcOrgao {
            get {
                return this.identcOrgaoField;
            }
            set {
                this.identcOrgaoField = value;
                this.RaisePropertyChanged("IdentcOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CNPJBase_CodErro CNPJBaseOrgaoPagdr {
            get {
                return this.cNPJBaseOrgaoPagdrField;
            }
            set {
                this.cNPJBaseOrgaoPagdrField = value;
                this.RaisePropertyChanged("CNPJBaseOrgaoPagdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NU_CodErro NUAvebcSCC {
            get {
                return this.nUAvebcSCCField;
            }
            set {
                this.nUAvebcSCCField = value;
                this.RaisePropertyChanged("NUAvebcSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public IdentcMotvDesavebcContrto_CodErro IdentcMotvDesavebcContrto {
            get {
                return this.identcMotvDesavebcContrtoField;
            }
            set {
                this.identcMotvDesavebcContrtoField = value;
                this.RaisePropertyChanged("IdentcMotvDesavebcContrto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Grupo_ASCC012_ParclContrtoSCComplexType Grupo_ASCC012_ParclContrtoSCC {
            get {
                return this.grupo_ASCC012_ParclContrtoSCCField;
            }
            set {
                this.grupo_ASCC012_ParclContrtoSCCField = value;
                this.RaisePropertyChanged("Grupo_ASCC012_ParclContrtoSCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class CPF_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class IdentcServdr_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class IdentcOrgao_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class NU_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class IdentcMotvDesavebcContrto_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class Grupo_ASCC012_ParclContrtoSCComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NumParcl_CodErro numParclField;
        
        private MesAno_CodErro vencParclField;
        
        private string codErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NumParcl_CodErro NumParcl {
            get {
                return this.numParclField;
            }
            set {
                this.numParclField = value;
                this.RaisePropertyChanged("NumParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MesAno_CodErro VencParcl {
            get {
                return this.vencParclField;
            }
            set {
                this.vencParclField = value;
                this.RaisePropertyChanged("VencParcl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class NumParcl_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd")]
    public partial class MesAno_CodErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
                this.RaisePropertyChanged("CodErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd")]
    public partial class WSCC012RETCorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ASCC012RETComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASCC012RET", Order=0)]
        public ASCC012RETComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSTIPOS.xsd")]
    public partial class CabecalhoRespComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtHrRespostaField;
        
        private string statusProcessamentoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DtHrResposta {
            get {
                return this.dtHrRespostaField;
            }
            set {
                this.dtHrRespostaField = value;
                this.RaisePropertyChanged("DtHrResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusProcessamento {
            get {
                return this.statusProcessamentoField;
            }
            set {
                this.statusProcessamentoField = value;
                this.RaisePropertyChanged("StatusProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd")]
    public partial class WSCC012CorpoComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grupo_ASCC012_ConsigrioComplexType[] aSCC012Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo_ASCC012_Consigrio", Namespace="http://www.cip-bancos.org.br/ARQ/ASCC012.xsd", IsNullable=false)]
        public Grupo_ASCC012_ConsigrioComplexType[] ASCC012 {
            get {
                return this.aSCC012Field;
            }
            set {
                this.aSCC012Field = value;
                this.RaisePropertyChanged("ASCC012");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd")]
    public partial class WSCC012Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CabecalhoRespComplexType cabecalhoRespField;
        
        private WSCC012RETCorpoComplexType corpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CabecalhoRespComplexType CabecalhoResp {
            get {
                return this.cabecalhoRespField;
            }
            set {
                this.cabecalhoRespField = value;
                this.RaisePropertyChanged("CabecalhoResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WSCC012RETCorpoComplexType Corpo {
            get {
                return this.corpoField;
            }
            set {
                this.corpoField = value;
                this.RaisePropertyChanged("Corpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC012Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd", Order=0)]
        public CIPLibrary.SCC012Reference.WSCC012Request WSCC012Request;
        
        public WSCC012Request1() {
        }
        
        public WSCC012Request1(CIPLibrary.SCC012Reference.WSCC012Request WSCC012Request) {
            this.WSCC012Request = WSCC012Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSCC012Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/WSCC012.xsd", Order=0)]
        public CIPLibrary.SCC012Reference.WSCC012Response WSCC012Response;
        
        public WSCC012Response1() {
        }
        
        public WSCC012Response1(CIPLibrary.SCC012Reference.WSCC012Response WSCC012Response) {
            this.WSCC012Response = WSCC012Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCC012Channel : CIPLibrary.SCC012Reference.WSCC012, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCC012Client : System.ServiceModel.ClientBase<CIPLibrary.SCC012Reference.WSCC012>, CIPLibrary.SCC012Reference.WSCC012 {
        
        public WSCC012Client() {
        }
        
        public WSCC012Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCC012Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC012Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCC012Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIPLibrary.SCC012Reference.WSCC012Response1 CIPLibrary.SCC012Reference.WSCC012.WSCC012(CIPLibrary.SCC012Reference.WSCC012Request1 request) {
            return base.Channel.WSCC012(request);
        }
        
        public CIPLibrary.SCC012Reference.WSCC012Response WSCC012(CIPLibrary.SCC012Reference.WSCC012Request WSCC012Request) {
            CIPLibrary.SCC012Reference.WSCC012Request1 inValue = new CIPLibrary.SCC012Reference.WSCC012Request1();
            inValue.WSCC012Request = WSCC012Request;
            CIPLibrary.SCC012Reference.WSCC012Response1 retVal = ((CIPLibrary.SCC012Reference.WSCC012)(this)).WSCC012(inValue);
            return retVal.WSCC012Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CIPLibrary.SCC012Reference.WSCC012Response1> CIPLibrary.SCC012Reference.WSCC012.WSCC012Async(CIPLibrary.SCC012Reference.WSCC012Request1 request) {
            return base.Channel.WSCC012Async(request);
        }
        
        public System.Threading.Tasks.Task<CIPLibrary.SCC012Reference.WSCC012Response1> WSCC012Async(CIPLibrary.SCC012Reference.WSCC012Request WSCC012Request) {
            CIPLibrary.SCC012Reference.WSCC012Request1 inValue = new CIPLibrary.SCC012Reference.WSCC012Request1();
            inValue.WSCC012Request = WSCC012Request;
            return ((CIPLibrary.SCC012Reference.WSCC012)(this)).WSCC012Async(inValue);
        }
    }
}
